### ISSUE TITLE
Support aircon without /skyfi

### ISSUE THREAD

**Issue by lapoPaolacci** [yenoiwesa/homebridge-daikin-airbase#16]
Plugin detect my 2 aircon but give 404, because the url to be call is http://IP/common/basic_info without skyfi before common

**Comment by yenoiwesa** [comment]
Hi @lapoPaolacci ,

Could you please check the model number of your Daikin Wifi Module please?
This platform only supports BRP15B61 (the Daikin Airbase controller).

**Comment by lapoPaolacci** [comment]
Hi,
I think I have BRP069B41 :(

Best regards

**Comment by yenoiwesa** [comment]
Ah too bad. Your Wifi Controller has a different API and feature set. There are other plugins available on npm for yours. Search for homebridge skyfi.

Sorry!
