### ISSUE TITLE
[Feature] Optional periodical background polling with a configurable interval

### ISSUE THREAD

**Issue by TimofeyK** [yenoiwesa/homebridge-daikin-airbase#3]
The plugin refreshes current Aircon state when Home app is open but if the Aircon was controlled outside of HomeKit e.g. from a wired wall controller, HomeKit will not see the change and therefore it's not possible to use the state as a trigger for automations. 

With Cmd4 plugin I used its option to periodically poll specified characteristics so HomeKit would "notice" the change after specified interval. I use this to change light bulb colour depending on cool/heat mode

**Comment by yenoiwesa** [comment]
Hey @TimofeyK 👋 

Thanks for raising this feature request too!

So I'd like to have the default configuration of the plugin "just work" with no fuss for most people. Your use case does sound legit: being able to do automations based on the aircon state or its temperature reading. So what I am thinking is to make the polling behaviour **default** in the plugin (and maybe just have an option to change its interval, with `0` meaning no polling).

Now, I'd like to make sure that I don't hammer the airbase device with polling requests all the time. Would a minimum polling interval of 1 min be sufficient for you? I would then probably have the default set to poll every 5 mins. But basically the precision of the interval would be in minutes. Is that okay?

**Comment by TimofeyK** [comment]
1 minute minimum interval is fine. I think I had mine at 2 min (already removed my old integration). 5 min default also seems very reasonable. Certainly does not need seconds precision

Thank you!

**Comment by yenoiwesa** [comment]
Hey @TimofeyK 👋 

I just released version `1.3.0` of the plugin with polling support. The default is set to an interval of 5 minutes between updates.

Let me know if that new version works for you!

**Comment by TimofeyK** [comment]
Tested a basic automation and it works pretty well. You nailed it again! :)

**Comment by yenoiwesa** [comment]
I'll leave the issue open for a week or so to allow you some time to find bugs, and if everything's clear I'll close it then.

Cheers!

**Comment by yenoiwesa** [comment]
Alright I will now close this issue since it seems to work fine :-)
