### ISSUE TITLE
Disable zones in home bridge [Enhancement]

### ISSUE THREAD

**Issue by cemilbrowne** [yenoiwesa/homebridge-daikin-airbase#34]
Hi,

Now that I’ve started playing with zones - it’d be amazing to be able to disable a zone.  My Airbase exposes 8 zones, of which only 3 are actually mapped to rooms in the house, so I end up with pointless switches…

Thanks!

**Comment by TimofeyK** [comment]
@cemilbrowne this is done via field settings on your air conditioner. The airbase controller reads the number of zones from the air conditioner zone controller and reports to the plugin so the plugin generates the correct number of zones

Google it or check the manual for your model

**Comment by yenoiwesa** [comment]
Thanks for answering this one @TimofeyK 😃 

@cemilbrowne as mentioned above, this is a Daikin level setting that your installer normally takes care of, but you can do it yourself easily in field settings.

I will close this ticket.

**Comment by cemilbrowne** [comment]
Thanks both!
