### ISSUE TITLE
Adding additional Daikin Airbase modules

### ISSUE THREAD

**Issue by pxg14** [yenoiwesa/homebridge-daikin-airbase#36]
Hi, thanks for the great work allowing people to add their Daikin air conditioners to HomeKit. 

One question, what is the syntax for adding an additional Daikin Airbase module to the plug-in settings? I've tried separating names and IP addresses using commas and semi-colons but that doesn't work.
Alternatively, what would a config file look like with two Airbase modules? 

Something like this?

   "name": "DaikinAPxxxxx",
            "hostname": "192.168.x.x",
            "pollingInterval": 5,
            "useIndividualZoneControls": false,
            "platform": "DaikinAirbase"
        },
        {
            "name": "DaikinAPxxxxx",
            "hostname": "192.168.x.x",
            "pollingInterval": 5,
            "useIndividualZoneControls": false,
            "platform": "DaikinAirbase"

Thanks

Peter

**Comment by yenoiwesa** [comment]
Hi @pxg14 👋 

The correct syntax if you want to enforce specific hostnames with multiple Airbases is:

```json
{
    "platform": "DaikinAirbase",
    "name": "Daiking Airbase",
    "hostname": ["192.168.x.x",  "192.168.x.x"]
}
```

All the other options you are specifying are the default values and thus you do not need to explicitly define them.

As a matter of fact, you should also be able to just use:

```json
{
    "platform": "DaikinAirbase",
    "name": "Daiking Airbase"
}
```

When you do not mention any hostnames, the plugin will scan your network to find Airbase modules automatically, like the Daikin Airbase mobile app does.

Let me know if that solves your problem.

Cheers!

**Comment by yenoiwesa** [comment]
No you cannot provide names. You might be misunderstood by what `name` means in the context of that configuration. It's just the name of the Homebridge Platform for the purpose of logging. This is not the name of the accessories in HomeKit.

The plugin will automatically use the unique name of your Airbase as setup in the Daikin Airbase app. You can also change the display name of your accessories in the Home app directly.

**Comment by pxg14** [comment]
ok, got it. Thanks!
For the second Airbase module, these errors are generated:

[18/01/2022, 18:05:36] [DaikinAirbase] TypeError: Cannot read properties of undefined (reading 'ok')
    at DaikinAircon.sendRequest (/usr/local/lib/node_modules/homebridge-daikin-airbase/src/airbase-controller.js:129:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
    at DaikinAircon.init (/usr/local/lib/node_modules/homebridge-daikin-airbase/src/airbase-controller.js:146:40)
    at RetryOperation._fn (/usr/local/lib/node_modules/homebridge-daikin-airbase/src/daikin-airbase-platform.js:106:21)
[18/01/2022, 18:05:36] [DaikinAirbase] Found 2 devices

One Airbase is ok, one isn't. Any ideas?

Thanks
Peter

**Comment by yenoiwesa** [comment]
Are you sure they both are BRP15B61 models @pxg14 ?

**Comment by pxg14** [comment]
One could be different. I don't have a ladder tall enough right now to reach the 2nd module. I gather it must be that specific model?

**Comment by pxg14** [comment]
ok, thanks.

**Comment by yenoiwesa** [comment]
Have you found out what model you have for your second unit @pxg14 ? And with what phone app you can control it?

**Comment by pxg14** [comment]
Hi, it's a BRP072C42. I tried to connect to it using a different plug-in but errors received.

**Comment by yenoiwesa** [comment]
This plugin seems to support model BRP072C42 https://github.com/cbrandlehner/homebridge-daikin-local, however it seems you must ensure it's on the latest firmware version.

**Comment by yenoiwesa** [comment]
(Sorry I hit close issue by mistake 🤦 )

**Comment by pxg14** [comment]
I tried that plugin and on latest firmware but have errors still received

**Comment by yenoiwesa** [comment]
That's a shame 😞 Unfortunately there isn't much I can do to help you beyond that. I would suggest to open an issue on that plugin's repository to have the maintainers try to help you.

Another, more radical, option would be to replace your current BRP072C42 with a Daikin Airbase (BRP15B61) if your aircon is compatible with this newer model.

**Comment by pxg14** [comment]
Yep, I've raised an issue. At least one other person is also having the same issue.

**Comment by yenoiwesa** [comment]
Cheers @pxg14, in that case I will close this issue since the original question got answered :-)
Good luck with the integration of the other plugin!
