### ISSUE TITLE
Install without fan mode and dry mode switches

### ISSUE THREAD

**Issue by mwhoops** [yenoiwesa/homebridge-daikin-airbase#52]
Is there a way to install this plugin through Homebridge that does not include the fan mode and dry mode switches, so that that aren't visible in HomeKit?

**Comment by yenoiwesa** [comment]
You're in luck Mister Whoops! Yes it is possible.
As per the [README.md](https://github.com/yenoiwesa/homebridge-daikin-airbase) file, you can add to your platform configuration the following lines:
```json
"platforms": [
  {
    "platform": "DaikinAirbase",
    "name": "Daiking Airbase"
    ...
    "overrides" {
      "fanModeSupported": false,
      "dryModeSupported": false
  }
]
```

Cheers

**Comment by mwhoops** [comment]
Hi, unfortunately the accessories still appear in HomeKit.

Could you please review the config and let me know if I’ve added it incorrectly?
![B6688886-49A9-4D05-9CB1-BDF1ABCA8ACA](https://user-images.githubusercontent.com/130896214/232728198-0515cba5-34c1-418a-998e-393aeed291e1.jpeg)

Am I able to add the overrides after the plug-in has been been installed or should it be done during install?

**Comment by yenoiwesa** [comment]
You configuration is looking fine. It's very likely that if the platform installed these accessories once, it will keep using them yes. So you might have to purge your accessory cache to reset the state of the platform.

**Comment by mwhoops** [comment]
Purging the accessory cache worked! Thank you very much.
