### ISSUE TITLE
Turn on / off after pairing with Homebridge

### ISSUE THREAD

**Issue by keertisomu** [yenoiwesa/homebridge-daikin-airbase#56]
Hi,

I was able to successfully install homebridge + daikin airbase. After that with the default configuration the plugin was able to detect both my daikin aircons. I am trying to setup my automation where particular time of the day I want to switch ON the aircon but the HomeKit automation does not have a turn ON , but only a turn off.

Basically I want to control that first tile (Heat / Cool) via my homekit app.  Any advice or ideas?
homebridge screenshot
 ![Screenshot from 2024-07-06 13-14-32](https://github.com/yenoiwesa/homebridge-daikin-airbase/assets/32979227/c6834bf8-a9ad-4d89-b7eb-37caf1d3b0e3)

if you see in this screenshot (homekit) , I don't get an option to turn ON the aircon ? 
![automation](https://github.com/yenoiwesa/homebridge-daikin-airbase/assets/32979227/254a4d0a-9929-4822-b2c3-94a51153f837)

Thanks.

**Comment by yenoiwesa** [comment]
Hi @keertisomu, 

Here is what a similar automation looks like for me in Apple Home. Make sure to select the Heater/Cooler device as source (which I think you did) and then click on it to select the heating mode and the desired temperature.

<img width="576" alt="Screenshot 2024-07-06 at 13 26 46" src="https://github.com/yenoiwesa/homebridge-daikin-airbase/assets/1464666/bdad7804-0663-4243-9c58-435cc6a0b755">

<img width="576" alt="Screenshot 2024-07-06 at 13 27 14" src="https://github.com/yenoiwesa/homebridge-daikin-airbase/assets/1464666/b1d17b24-ff4e-41a5-9ca0-2bf45037dbb3">

<img width="576" alt="Screenshot 2024-07-06 at 13 27 20" src="https://github.com/yenoiwesa/homebridge-daikin-airbase/assets/1464666/c8bc5e16-ff00-4c13-9910-525f890f50e2">

**Comment by keertisomu** [comment]
Thanks @yenoiwesa 👍  , I had to select the accessory after entering into the automation wizard which I wasn't.
